# Generated by Django 3.2.15 on 2022-11-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='vendor',
            new_name='vendor1',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='vendor',
            new_name='vendor1',
        ),
    ]
