# Generated by Django 3.2.15 on 2022-11-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20221105_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='vendor1',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='vendor1',
            new_name='vendor',
        ),
    ]
